name: CI

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        docker: ['ps2dev', 'fjtrujy']
    runs-on: ubuntu-latest
    container: ${{ matrix.docker }}/ps2dev:latest
    steps:
    - name: Install dependencies
      run: |
        apk add build-base git zip gawk
        wget -O ${PS2SDK}/samples/Makefile.iopglobal https://raw.githubusercontent.com/ps2dev/ps2sdk/master/samples/Makefile.iopglobal_sample

    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow

    - name: Set up environment
      if: matrix.docker == 'fjtrujy'
      run: |
        echo "IOP_TOOL_PREFIX=mipsel-ps2-irx-" >> $GITHUB_ENV
        echo "IOP_PREFIX=mipsel-ps2-irx-" >> $GITHUB_ENV
 
    - name: Install ps2eth
      run: |
        git clone https://github.com/ps2dev/ps2eth.git
        cd ps2eth && make clean all install

    - name: Compile wLaunchELF
      run: make
    
    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: wLaunchELF-${{ steps.slug.outputs.sha8 }}-${{ matrix.docker }}
        path: BOOT.ELF

    - name: Create release
      if: github.ref == 'refs/heads/master'
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        title: "Latest development build"
        files: BOOT.ELF
