name: CI

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:latest
    steps:
      - name: Install dependencies
        run: |
          apk add build-base git zip bash

      - uses: actions/checkout@v3
      - run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git fetch --prune --unshallow

      - name: Revert sdk
        run: |
          git clone https://github.com/ps2dev/ps2sdk
          cd ps2sdk
          git reset --hard 01f3db7f01f50f656387b1a5de59b0e9eb88a69d
          make release

      - name: Compile wLaunchELF
        run: |
          git reset --hard e4fa0ec7a86e63d0469593f76a48a49462121ad6
          make
          git ls-files -i --exclude-standard -c

      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

      - name: Upload artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          name: wLaunchELF-${{ steps.slug.outputs.sha8 }}
          path: BOOT.ELF

      - name: Create release
        if: github.ref == 'refs/heads/master'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Latest development build"
          files: BOOT.ELF
